services:
  # Backend API
  - type: web
    name: joltcab-api
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        fromDatabase:
          name: joltcab-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://joltcab.pages.dev
      - key: CORS_ORIGIN
        value: https://joltcab.pages.dev,http://localhost:5173
    healthCheckPath: /api/v1/health

# MongoDB Database
databases:
  - name: joltcab-mongodb
    databaseName: joltcab
    user: joltcab_user
    plan: starter
